# Generated by Django 2.2.4 on 2019-11-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190909_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ('id', 'priority')},
        ),
        migrations.AddField(
            model_name='teams',
            name='fallback_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_teams', to='teams.Teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
