# Generated by Django 2.2.4 on 2019-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_opportunity_teams'),
        ('events', '0003_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='opportunities',
            field=models.ManyToManyField(blank=True, related_name='event_opportunity', to='opportunity.Opportunity'),
        ),
    ]
