# Generated by Django 2.2.4 on 2019-11-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunity', '0004_opportunity_teams'),
        ('teams', '0004_auto_20191112_1059'),
        ('listings', '0001_initial'),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='listings.Listing'),
        ),
        migrations.AddField(
            model_name='interest',
            name='matching_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='teams.Teams'),
        ),
        migrations.AddField(
            model_name='interest',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='opportunity.Opportunity'),
        ),
    ]
