# Generated by Django 2.2.4 on 2019-11-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0002_auto_20191113_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='deals.Deal'),
        ),
    ]
