# Generated by Django 2.2.4 on 2019-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_document_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, max_length=64, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, max_length=64, null=True, verbose_name='Longitude'),
        ),
    ]
