# Generated by Django 2.2.4 on 2019-11-12 21:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_account_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('start_on', models.DateTimeField(blank=True, null=True)),
                ('end_on', models.DateTimeField(blank=True, null=True)),
                ('zumper_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('zumper_agent_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('zumper_building_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('zumper_listing_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('zumper_brokerage_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('features', models.BigIntegerField(blank=True, choices=[(1, 'APPLICATION_FEE'), (2, 'ASSISTED_LIVING'), (3, 'SPECIALS'), (4, 'INCOME_RESTRICTED'), (5, 'SECTION_8'), (6, 'SENIOR_LIVING'), (7, 'SHORT_TERM'), (8, 'STUDENT_HOUSING'), (9, 'VIP'), (10, 'SWEET_DEAL'), (11, 'SELECT'), (12, 'SELECT_MONETIZED'), (13, 'PAID_PROMOTION'), (14, 'META_NO_INDEX'), (15, 'REX'), (16, 'EXCLUSIVE'), (17, 'MM_EXCLUDE'), (18, 'MM_PREVENT'), (19, 'DIRECT_DEAL'), (20, 'HAS_UNITS'), (21, 'BOOK_NOW'), (22, 'THIRD_PARTY_PAID'), (23, 'LARGE_LIST_CARD'), (24, 'REQ_PHONE_NUMBER'), (25, 'REQ_MOVE_IN_DATE'), (26, 'REQ_CUSTOM_MSG'), (27, 'FACEBOOK_EXCLUDE'), (28, 'LEASELOCK'), (29, 'FEATURED'), (30, 'TOUR')])),
                ('feed_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('flat_revenue', models.IntegerField(blank=True, null=True)),
                ('flat_revenue_per', models.IntegerField(blank=True, null=True)),
                ('lead_revenue', models.IntegerField(blank=True, null=True)),
                ('lead_revenue_cap', models.IntegerField(blank=True, null=True)),
                ('lead_revenue_cap_per', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('opportunity_id', models.CharField(blank=True, max_length=128, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', to='accounts.Account')),
            ],
        ),
    ]
