# Generated by Django 2.2.4 on 2019-11-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_auto_20191112_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('agent_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Agent Email')),
                ('brokerage_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Brokerage Key')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_exclusive', models.NullBooleanField()),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_routes', to='teams.Teams')),
            ],
        ),
    ]
